### PR TITLE
Support for multiple attendees

### PR DESCRIPTION
**Pull request by gk159yo**

### CODE REVIEW

**Comment by gk159yo** [comment]
lol... i think i got rid of a new line so the coverage went down. @brh55 would you like me to insert a new blank line to maintain coverage?

**Comment by brh55** [comment]
@gk159yo lol it might be the lines covered in relation to the entire CB, but I wouldn't worry about it. But this looks good (code style, no breaking changes, etc)! I'll merge in, thanks!

**Comment by brh55** [comment]
Merged into v0.2.2 and published on NPM @gk159yo  thank you again!

**Comment by gk159yo** [comment]
@brh55 np. Thank you for publishing on NPM!

**Pull request merged**
